#!/bin/sh
#
# Spybot Command and Control Server controller script
#
NAME=spybotccserverctl
DAEMON=jsvc
JAR=/usr/local/lib/spybotccserver/spybotccserver.jar
CLASS=Server
DESC="Spybot Command and Control Server"

test -f $JAR || exit 1

case "$1" in
  start)
    echo "Starting $DESC"
    $DAEMON -home /usr/lib/jvm/default-java -classpath $JAR $CLASS
    ;;
  stop)
    echo "Stopping $DESC"
    $DAEMON stop
    ;;
  restart)
    echo "Restarting $DESC"
    $DAEMON restart
    ;;
  *)
    echo "usage: $NAME start|stop|restart"
    exit 2
    ;;
esac

exit 0
