#!/bin/sh
#
# Spybot Command and Control Server controller script
#

NAME=spybotccserverctl
DESC="Spybot Command and Control Server"
EXEC=/usr/bin/jsvc
CLASSPATH=/usr/share/java/commons-daemon.jar:/usr/local/lib/spybotccserver/spybotccserver.jar
CLASS=com.atomatica.spybotccserver.Spybotccserver
JAVA_HOME=/usr/lib/jvm/jdk1.6.0_32
PID=/tmp/spybotccserver.pid
LOG_OUT=/var/log/spybotccserver.log
LOG_ERR=/var/log/spybotccserver-error.log

test -f $EXEC || exit 1

do_exec() {
    $EXEC -home "$JAVA_HOME" -cp $CLASSPATH -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS
}

case "$1" in
    start)
        echo "Starting $DESC"
        do_exec
        ;;
    stop)
        echo "Stopping $DESC"
        do_exec "-stop"
        ;;
    restart)
        if [ -f "$PID" ]; then
            echo "Restarting $DESC"
            do_exec "-stop"
            do_exec
        else
            echo "$DESC not running, will do nothing"
            exit 1
        fi
        ;;
    *)
        echo "usage: $NAME start|stop|restart" >&2
        exit 2
        ;;
esac

exit 0
